service: aws-cart-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: dev
  environment:
    DBHOST: aws-cart-api-dev-cartdb-wwpluzyxevt5.cnoycz1qw4xb.eu-west-1.rds.amazonaws.com
    DBPORT: 5432
    DBNAME: postgres
    DBUSER: postgres
    DBPASSWORD: rds12345

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
resources:
  Resources:
    CartDB:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: cart
        AllocatedStorage: '20'
        VPCSecurityGroups:
          - !GetAtt DBEC2SecurityGroup.GroupId
        DBInstanceClass: db.t4g.micro
        Engine: postgres
        MasterUsername: postgres
        MasterUserPassword: 'rds12345'
        PubliclyAccessible: true
        BackupRetentionPeriod: 0
      DeletionPolicy: Snapshot

    DBEC2SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: PublicAccessDBGroup
        GroupDescription: Allow postgres inbound traffic
        SecurityGroupIngress:
          - IpProtocol: tcp
            CidrIp: 0.0.0.0/0
            FromPort: 5432
            ToPort: 5432